# Generated by Django 5.1.3 on 2024-11-20 20:29

import authuser.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_user_is_active_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authuser.models.CustomUserManager()),
            ],
        ),
    ]
